/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Artifact */
        post: operations["post_artifact_v1_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_v1_batches_get"];
        put?: never;
        /** Post Batch */
        post: operations["post_batch_v1_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_batches__batch_id__runs_get"];
        put?: never;
        /** Post Run */
        post: operations["post_run_v1_batches__batch_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}/sources/{source}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Source */
        post: operations["complete_source_v1_batches__batch_id__sources__source__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Audit */
        get: operations["get_case_audit_v1_cases__case_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Close */
        post: operations["post_close_v1_cases__case_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Decision
         * @description A human supervisor decides on the current version. Nothing is executed.
         *
         *     Any authenticated reader reaches the policy so that refused attempts (wrong role,
         *     self-approval, stale version...) are audited; only supervisors can succeed.
         */
        post: operations["post_decision_v1_cases__case_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Recommendation
         * @description An analyst proposes; adopting an investigation draft requires a SUPPORTED review.
         */
        post: operations["post_recommendation_v1_cases__case_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_v1_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/results/{ordinal}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Case */
        post: operations["post_case_v1_runs__run_id__results__ordinal__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/results/{ordinal}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Investigation
         * @description Request a read-only investigation; repeating it without new evidence is idempotent.
         */
        post: operations["post_investigation_v1_runs__run_id__results__ordinal__investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @description What a recommendation proposes to a person. None of them moves money.
         * @enum {string}
         */
        Action: "ACCEPT_PROBABLE_MATCH" | "CLOSE_AS_EXPLAINED" | "REQUEST_PROVIDER_INFO" | "REQUEST_ADJUSTMENT_REVIEW";
        /** ArtifactIn */
        ArtifactIn: {
            /** Content */
            content: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "internal_ledger" | "provider_report";
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Resource Id */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Version */
            resource_version: number | null;
        };
        /** AuditTrailOut */
        AuditTrailOut: {
            /** Audit */
            audit: components["schemas"]["AuditEntryOut"][];
            /** Case */
            case: {
                [key: string]: unknown;
            };
            /** Decisions */
            decisions: components["schemas"]["DecisionRecordOut"][];
            /** Investigations */
            investigations: {
                [key: string]: unknown;
            }[];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationOut"][];
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
        };
        /** BatchIn */
        BatchIn: {
            /** Batch Id */
            batch_id: string;
            /** Business Timezone */
            business_timezone: string;
            /** Currency */
            currency: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /**
             * Left Source
             * @default internal_ledger
             * @enum {string}
             */
            left_source: "internal_ledger" | "provider_report";
            /** Merchant Account */
            merchant_account: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Right Source
             * @default provider_report
             * @enum {string}
             */
            right_source: "internal_ledger" | "provider_report";
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** BatchOut */
        BatchOut: {
            /** Batch Id */
            batch_id: string;
            /** Business Timezone */
            business_timezone: string;
            /** Currency */
            currency: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /** Left Complete */
            left_complete: boolean;
            /**
             * Left Source
             * @default internal_ledger
             * @enum {string}
             */
            left_source: "internal_ledger" | "provider_report";
            /** Merchant Account */
            merchant_account: string;
            /** Provider Id */
            provider_id: string;
            /** Right Complete */
            right_complete: boolean;
            /**
             * Right Source
             * @default provider_report
             * @enum {string}
             */
            right_source: "internal_ledger" | "provider_report";
            /** Version */
            version: number;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** BatchSummary */
        BatchSummary: {
            /** Batch Id */
            batch_id: string;
            /** Currency */
            currency: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /** Left Complete */
            left_complete: boolean;
            /** Merchant Account */
            merchant_account: string;
            /** Provider Id */
            provider_id: string;
            /** Right Complete */
            right_complete: boolean;
            /** Version */
            version: number;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** CaseOpened */
        CaseOpened: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Created */
            created: boolean;
        };
        /** CaseOut */
        CaseOut: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Case Ref */
            case_ref: string;
            /** Closed Reason */
            closed_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decisions */
            decisions: components["schemas"]["DecisionRecordOut"][];
            /** Opened By */
            opened_by: string;
            /** Ordinal */
            ordinal: number;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationOut"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Is Latest */
            run_is_latest: boolean;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** CaseSummary */
        CaseSummary: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Case Ref */
            case_ref: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** CloseIn */
        CloseIn: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "APPROVE" | "REJECT" | "NEEDS_INFORMATION";
        /** DecisionIn */
        DecisionIn: {
            decision: components["schemas"]["Decision"];
            /** Expected Version */
            expected_version: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Approved Version */
            approved_version: number;
            /** Decision */
            decision: string;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Operational Effect */
            operational_effect: string;
            /** Replayed */
            replayed: boolean;
        };
        /** DecisionRecordOut */
        DecisionRecordOut: {
            /** Approver */
            approver: string;
            /** Case Version */
            case_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationAccepted */
        InvestigationAccepted: {
            /** Created */
            created: boolean;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "requested" | "existing";
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Case Ref */
            case_ref: string;
            /** Case Version */
            case_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /** Record */
            record: {
                [key: string]: unknown;
            };
            /** Requested By */
            requested_by: string;
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /** ReadyChecks */
        ReadyChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "fail" | "timeout";
            /**
             * Messaging
             * @enum {string}
             */
            messaging: "ok" | "fail" | "timeout";
            /**
             * Vector
             * @enum {string}
             */
            vector: "ok" | "fail" | "timeout";
        };
        /** ReadyResponse */
        ReadyResponse: {
            checks: components["schemas"]["ReadyChecks"];
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** ReceiptOut */
        ReceiptOut: {
            /** Accepted */
            accepted: number;
            /** Artifact Id */
            artifact_id: number;
            /** Conflicts */
            conflicts: number;
            /** Content Hash */
            content_hash: string;
            /** Duplicates */
            duplicates: number;
            /** Rejected */
            rejected: number;
            /** Rejections */
            rejections: components["schemas"]["RejectionOut"][];
            /** Replayed */
            replayed: boolean;
            /** Row Count */
            row_count: number;
        };
        /** RecommendationCreated */
        RecommendationCreated: {
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /**
             * Status
             * @constant
             */
            status: "PENDING";
        };
        /** RecommendationIn */
        RecommendationIn: {
            action: components["schemas"]["Action"];
            /** Expected Version */
            expected_version: number;
            /** Investigation Id */
            investigation_id?: string | null;
            /** Rationale */
            rationale: string;
        };
        /** RecommendationOut */
        RecommendationOut: {
            /** Action */
            action: string;
            /** Case Version */
            case_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Investigation Id */
            investigation_id: string | null;
            /** Proposer */
            proposer: string;
            /** Rationale */
            rationale: string;
            /** Review Result */
            review_result: string;
            /** Status */
            status: string;
        };
        /** RejectionOut */
        RejectionOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Row Number */
            row_number: number;
        };
        /** ResultOut */
        ResultOut: {
            /** Alternatives */
            alternatives: number[];
            /** Amount Difference Minor */
            amount_difference_minor: number | null;
            /** Discrepancy Types */
            discrepancy_types: string[];
            /** Explanation */
            explanation: string;
            /** Left Ids */
            left_ids: number[];
            /** Match Status */
            match_status: string;
            /** Operation Type */
            operation_type: string;
            /** Ordinal */
            ordinal: number;
            /** Payment Ref */
            payment_ref: string;
            /** Right Ids */
            right_ids: number[];
            /** Rule */
            rule: string;
            /** Score */
            score: number | null;
        };
        /** ResultPage */
        ResultPage: {
            /** Items */
            items: components["schemas"]["ResultOut"][];
            /** Next After */
            next_after: number | null;
        };
        /** RunAccepted */
        RunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Number */
            run_number: number;
            /**
             * Status
             * @constant
             */
            status: "requested";
        };
        /** RunOut */
        RunOut: {
            /** Batch Id */
            batch_id: string;
            /** Completed At */
            completed_at: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Observation Count */
            observation_count: number | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Requested By */
            requested_by: string;
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Number */
            run_number: number;
            /** Snapshot Hash */
            snapshot_hash: string | null;
            /** Status */
            status: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Completed At */
            completed_at: string | null;
            /** Observation Count */
            observation_count: number | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Number */
            run_number: number;
            /** Snapshot Hash */
            snapshot_hash: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    post_artifact_v1_artifacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_v1_batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_batch_v1_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_batches__batch_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_v1_batches__batch_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_source_v1_batches__batch_id__sources__source__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
                source: "internal_ledger" | "provider_report";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_v1_cases_get: {
        parameters: {
            query?: {
                status?: ("OPEN" | "HUMAN_REVIEW" | "APPROVED" | "REJECTED" | "NEEDS_INFORMATION" | "CLOSED") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_audit_v1_cases__case_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_close_v1_cases__case_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_decision_v1_cases__case_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recommendation_v1_cases__case_id__recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_v1_runs__run_id__results_get: {
        parameters: {
            query?: {
                match_status?: ("EXACT" | "PROBABLE" | "UNMATCHED" | "NOT_EVALUATED") | null;
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_case_v1_runs__run_id__results__ordinal__cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOpened"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_investigation_v1_runs__run_id__results__ordinal__investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
